import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { closeTranscriptDbs, openTranscriptDb } from '../../src/transcripts/database.js';
import { runIndexPass } from '../../src/transcripts/index-pass.js';
import { NAME_KIND, readOpeningAsk, readSessionNaming } from '../../src/transcripts/parse.js';
import { encodeProjectDir } from '../../src/transcripts/paths.js';

let dir: string;
let projectsDir: string;
let dbPath: string;
const PROJECT_ROOT = '/repo/knowl';
/** Derived rather than hardcoded, for the same reason as index-pass.test.ts. */
const ENCODED_ROOT = encodeProjectDir(path.resolve(PROJECT_ROOT));

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'knowl-naming-'));
  projectsDir = path.join(dir, 'projects');
  dbPath = path.join(dir, 'transcripts.db');
  await fs.mkdir(path.join(projectsDir, ENCODED_ROOT), { recursive: true });
});

afterEach(async () => {
  await closeTranscriptDbs();
  await fs.rm(dir, { recursive: true, force: true }).catch(() => {});
});

const naming = (entry: Record<string, unknown>) => JSON.stringify(entry) + '\n';
const line = (role: 'user' | 'assistant', text: string) =>
  JSON.stringify({ type: role, timestamp: '2026-08-03T10:00:00Z', message: { content: text } }) + '\n';

async function write(name: string, body: string) {
  await fs.writeFile(path.join(projectsDir, ENCODED_ROOT, name), body);
}
async function append(name: string, body: string) {
  await fs.appendFile(path.join(projectsDir, ENCODED_ROOT, name), body);
}
async function fileRow(sessionId: string) {
  const client = await openTranscriptDb(dbPath);
  return (await client.execute({
    sql: 'SELECT display_name, name_kind, opening FROM transcript_files WHERE session_id = ?',
    args: [sessionId],
  })).rows[0];
}
const pass = () => runIndexPass({ projectRoot: PROJECT_ROOT, dbPath, projectsDir });

describe('readSessionNaming', () => {
  it('reads a user rename at the highest rank', () => {
    expect(readSessionNaming({ type: 'custom-title', customTitle: 'ui-trial-screen' }))
      .toEqual({ name: 'ui-trial-screen', kind: NAME_KIND.custom });
  });

  it('reads an agent name below a rename', () => {
    expect(readSessionNaming({ type: 'agent-name', agentName: 'explorer' }))
      .toEqual({ name: 'explorer', kind: NAME_KIND.agent });
  });

  it('reads a generated title at the lowest rank', () => {
    expect(readSessionNaming({ type: 'ai-title', aiTitle: 'Generated title about buttons' }))
      .toEqual({ name: 'Generated title about buttons', kind: NAME_KIND.ai });
  });

  it('ignores an entry with the right type but no usable value', () => {
    expect(readSessionNaming({ type: 'custom-title' })).toBeNull();
    expect(readSessionNaming({ type: 'custom-title', customTitle: '   ' })).toBeNull();
  });

  it('ignores ordinary transcript entries', () => {
    expect(readSessionNaming({ type: 'user', message: { content: 'hello' } })).toBeNull();
  });
});

// Measured against the real archive before these were written: 91 of 232 first user turns
// across every project on this machine open with an injected wrapper rather than the user's
// words. Storing those verbatim gives several sessions the identical, meaningless opening
// "Caveat: The messages below were generated by the user while running local commands".
describe('readOpeningAsk', () => {
  it('keeps an ordinary question as-is', () => {
    expect(readOpeningAsk('why did the reindex run out of memory?'))
      .toBe('why did the reindex run out of memory?');
  });

  it('skips the local-command caveat, which is boilerplate and not an ask', () => {
    expect(readOpeningAsk('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'))
      .toBeNull();
  });

  it('skips command stdout and other injected turns', () => {
    expect(readOpeningAsk('<local-command-stdout>files changed</local-command-stdout>')).toBeNull();
    expect(readOpeningAsk('<system-reminder>remember the thing</system-reminder>')).toBeNull();
    expect(readOpeningAsk('<task-notification>done</task-notification>')).toBeNull();
  });

  it('unwraps a slash command to the name and the user words', () => {
    expect(readOpeningAsk('<command-name>/goal</command-name>\n<command-message>goal</command-message>\n<command-args>make knowl work across repos</command-args>'))
      .toBe('/goal make knowl work across repos');
  });

  it('keeps a slash command with no arguments', () => {
    expect(readOpeningAsk('<command-name>/compact</command-name>\n<command-args></command-args>'))
      .toBe('/compact');
  });

  it('keeps prose that merely happens to start with a tag', () => {
    expect(readOpeningAsk('<Role>reviewer</Role> please audit this')).toBe('<Role>reviewer</Role> please audit this');
  });

  it('treats an empty message as no ask', () => {
    expect(readOpeningAsk('   ')).toBeNull();
  });
});

describe('naming captured during the index pass', () => {
  it('prefers a user rename over a generated title in the same file', async () => {
    await write('named.jsonl',
      naming({ type: 'ai-title', aiTitle: 'Generated title about buttons' }) +
      naming({ type: 'custom-title', customTitle: 'ui-trial-screen' }) +
      line('user', 'first real question'));

    await pass();

    const row = await fileRow('named');
    expect(row.display_name).toBe('ui-trial-screen');
    expect(Number(row.name_kind)).toBe(NAME_KIND.custom);
  });

  it('does not let a later generated title overwrite a rename', async () => {
    await write('named.jsonl',
      naming({ type: 'custom-title', customTitle: 'ui-trial-screen' }) +
      naming({ type: 'ai-title', aiTitle: 'Generated title about buttons' }));

    await pass();

    expect((await fileRow('named')).display_name).toBe('ui-trial-screen');
  });

  it('takes a later rename at the same rank', async () => {
    await write('named.jsonl', naming({ type: 'custom-title', customTitle: 'first-name' }));
    await pass();

    await append('named.jsonl', naming({ type: 'custom-title', customTitle: 'second-name' }));
    await pass();

    expect((await fileRow('named')).display_name).toBe('second-name');
  });

  // The incremental trap: rank has to survive a pass boundary, or an appended low-rank
  // entry silently demotes a name captured earlier.
  it('keeps a rename when a generated title arrives in a later pass', async () => {
    await write('named.jsonl', naming({ type: 'custom-title', customTitle: 'ui-trial-screen' }));
    await pass();

    await append('named.jsonl', naming({ type: 'ai-title', aiTitle: 'Generated title' }));
    await pass();

    expect((await fileRow('named')).display_name).toBe('ui-trial-screen');
  });

  it('records the first real user ask as the opening', async () => {
    await write('opened.jsonl',
      line('user', 'why did the reindex run out of memory?') +
      line('assistant', 'because the batch was sized by row count') +
      line('user', 'a later question'));

    await pass();

    expect((await fileRow('opened')).opening).toBe('why did the reindex run out of memory?');
  });

  it('skips an injected opening turn and takes the first real ask', async () => {
    await write('caveated.jsonl',
      line('user', '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>') +
      line('user', 'why did the reindex run out of memory?'));

    await pass();

    expect((await fileRow('caveated')).opening).toBe('why did the reindex run out of memory?');
  });

  it('resets naming when a file is rewritten', async () => {
    await write('named.jsonl', naming({ type: 'custom-title', customTitle: 'old-name' }) + line('user', 'a'));
    await pass();

    await write('named.jsonl', line('user', 'b'));  // shorter: a rewrite
    await pass();

    expect((await fileRow('named')).display_name).toBeNull();
  });
});
